### PR TITLE
Inject stack name  into userdata for nodepool workers

### LINKED ISSUE #727: Nodepools created with spot instances fail to register in cluster.
The new method of getting the `KUBE_AWS_STACK_NAME` from `aws:cloudformation:stack-name` tag  doesn't work with Spot Instances because these instances are not tagged by Cloudformation. 

`cfn-etcd-environment.service` fails to start without `KUBE_AWS_STACK_NAME` value in `/etc/environment`

### PR DESCRIPTION
**Pull request by redbaron**
Fixes #727

### CODE REVIEW

**Comment by mumoshu** [comment]
@redbaron Thanks!
This looks nice, too :+1:
Perhaps this method can also be enhanced to use ignition in the future? Then, I prefer this over #732.

**Comment by redbaron** [comment]
Whole UserData refactor was done as a preparation for Ingition

**Comment by mumoshu** [comment]
@redbaron Oh, I had not realized that! Thank you very much 👍
Just confirming but have you verified this to work with ASG-based node pools? (SpotFleet-based ones are ok as they were verified by @camilb)

File: filereader/texttemplate/texttemplate.go [hunk 1]
```diff
@@ -21,9 +22,27 @@ func Parse(filename string, funcs template.FuncMap) (*template.Template, error)
 			}
 			return content, nil
 		},
+		"toJSON": func(v interface{}) (string, error) {
```
Comment (mumoshu) [inline filereader/texttemplate/texttemplate.go]: `toJson` is already available through `Masterminds/sprig` according to https://github.com/Masterminds/sprig/blob/dba49a8d3a46ae8522f79e2c0241842d6ab613ca/defaults.go#L66
Could we use the one from sprig instead?

File: filereader/texttemplate/texttemplate.go [hunk 2]
```diff
@@ -21,9 +22,27 @@ func Parse(filename string, funcs template.FuncMap) (*template.Template, error)
...
+			data, err := json.Marshal(v)
+			return string(data), err
+		},
+		"execTemplate": func(name string, ctx interface{}) (string, error) {
```
Comment (mumoshu) [inline filereader/texttemplate/texttemplate.go]: Could we use [the `template` func](https://golang.org/pkg/text/template/#hdr-Nested_template_definitions) bundled in `text/template` instead?

File: filereader/texttemplate/texttemplate.go (hunk 1 above)
Comment (redbaron) [inline filereader/texttemplate/texttemplate.go]: I didn't check if it exists in  a code, because it is undocumented on their godoc page: https://godoc.org/github.com/Masterminds/sprig
 
so I am not sure we can rely on it being available all the time

File: filereader/texttemplate/texttemplate.go (hunk 2 above)
Comment (redbaron) [inline filereader/texttemplate/texttemplate.go]: that is a workaround for `template` not being a real function :)  You can not pipe or capture its result

File: filereader/texttemplate/texttemplate.go (hunk 1 above)
Comment (mumoshu) [inline filereader/texttemplate/texttemplate.go]: @redbaron I believe we can expect it to remain to be existing because it is used widely in many helm charts.

File: filereader/texttemplate/texttemplate.go (hunk 2 above)
Comment (mumoshu) [inline filereader/texttemplate/texttemplate.go]: Oh, good to know! Thanks 😄

**Comment by redbaron** [comment]
> Just confirming but have you verified this to work with ASG-based node pools?

No I didn't verify it. Your question made me check for UserData calls and I found that I forgot to update normal ASG worker userdata calls. It should be in sync now and givent that template they are calling is identical it should work, but I'd like to ask for e2e test  or apply it to a test cluster if you have it running locally.

File: filereader/texttemplate/texttemplate.go (hunk 1 above)
Comment (redbaron) [inline filereader/texttemplate/texttemplate.go]: they use their own version: https://github.com/kubernetes/helm/blob/dece57e0baa94abdba22c0e3ced0b6ea64a83afd/pkg/engine/engine.go#L82

Comment (mumoshu) [inline filereader/texttemplate/texttemplate.go]: Thanks for the good catch 👍 Let me also add that both sprig's and helm's implementations of `toJson` seems to swallow errors, which sounds problematic to me. I'm now convinced to have our own implementation!

**Comment by mumoshu** [comment]
@redbaron Thanks for the fix. Sure, I'll kick the E2E script before I go to sleep 🛌

**Comment by mumoshu** [comment]
E2E passed. Thanks for your contribution as always, @redbaron 👍
