### PR TITLE
Fixes #630 leading slash on s3:prefix removed to fix ListObject permi…

### LINKED ISSUE #630: ETCDADM-save.service failed
I have received an error upon creating kubernetes cluster. My testing setup:
- kube-aws: 0.9.6
- controller: 1; public subnet
- worker: 1; public subnet
- etcd: 1; private subnet; set version to: "3.1.3" based on the comment in the cluster.yaml (but it just installed the 2.3.7 version)

No issues returned after CF completed the provisioning of resources. But when I open the etcd server via my bastion host, the etcdadm-save.service failed to start. Upon looking on the logs:

`
core@ip-172-50-5-223 ~ $ systemctl status etcdadm-save.service
etcdadm-save.service - etcd snapshot
   Loaded: loaded (/etc/systemd/system/etcdadm-save.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-05-09 05:30:41 UTC; 20s ago
  Process: 18097 ExecStart=/opt/bin/etcdadm save (code=exited, status=1/FAILURE)
  Process: 18087 ExecStartPre=/usr/bin/systemctl is-active etcd-member.service (code=exited, status=0/SUCCESS)
 Main PID: 18097 (code=exited, status=1/FAILURE)
      CPU: 2.009s

May 09 05:30:39 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_upload_snapshot: uploading /var/run/coreos/etcdadm/snapshots/etcd0.db to s3://my-bucket-name/kube-aws-096/kube-aws/clusters/ha-096/instances/80bceda0-3476-11e7-9ed8-50a68a05d035/etcd-snapshots/snapshot.db
May 09 05:30:40 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: [442B blob data]
May 09 05:30:40 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_upload_snapshot: verifying the upload...
May 09 05:30:40 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_remote_snapshot_exists: checking existence of s3://my-bucket-name/kube-aws-096/kube-aws/clusters/ha-096/instances/80bceda0-3476-11e7-9ed8-50a68a05d035/etcd-snapshots/snapshot.db
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal etcdadm[18097]: /opt/bin/etcdadm: info: member_remote_snapshot_exists: s3://my-bucket-name/kube-aws-096/kube-aws/clusters/ha-096/instances/80bceda0-3476-11e7-9ed8-50a68a05d035/etcd-snapshots/snapshot.db does not exist
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: etcdadm-save.service: Main process exited, code=exited, status=1/FAILURE
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: Failed to start etcd snapshot.
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: etcdadm-save.service: Unit entered failed state.
May 09 05:30:41 ip-172-50-5-223.us-east-2.compute.internal systemd[1]: etcdadm-save.service: Failed with result 'exit-code'.

`

I did try the simulation of the policy given to the etcd instance and it seems the S3 permissions are not allowed. So I tried to modify the policy and just set the S3:* allow all for the sake of testing. And it works. 

Is this a bug on the etcd policy? the S3 url including the sub-directories exist*

### PR DESCRIPTION
**Pull request by jeremyd**
…ssion denied error during etcdadm save.

### CODE REVIEW

File: core/controlplane/config/stack_config.go [hunk 1]
```diff
@@ -124,8 +124,8 @@ func (c *StackConfig) EtcdSnapshotsS3PrefixRef() (string, error) {
 	if err != nil {
 		return "", fmt.Errorf("Error in EtcdSnapshotsS3Prefix : %v", err)
 	}
-	s3path := fmt.Sprintf(`{ "Fn::Join" : [ "", [ "%s/instances/", { "Fn::Select" : [ "2", { "Fn::Split": [ "/", { "Ref": "AWS::StackId" }]} ]}, "/etcd-snapshots" ]]}`, s3uri.Path)
-	return strings.TrimLeft(s3path, "/"), nil
```
Comment (mumoshu) [inline core/controlplane/config/stack_config.go]: 😱

**Comment by mumoshu** [comment]
@jeremyd LGTM. Thanks as always for your support 👍
